[#ftl]
[#-- macro generate Processing List Body Start--]
[#macro generatePlBody HspPlModel]
[#-- Here we must get the argument list and use it into the function --] 
[#assign functionName = HspPlModel.function]
[#assign args = ""]
[#list HspPlModel.libMethod as method ]
	[#if method.arguments??]
		[#list method.arguments as argument]
[#if argument.genericType == "struct"]
				[@generateStructCode argument/]
				[#assign value =argument.name ]
			[#else]
				[#if !argument.value?? ]
					 [#continue]
				[/#if]
				[#assign value =argument.value ]
			[/#if]

			[#if argument.addressOf]
				[#assign args+="&"+value ]
			[#else]
				[#assign args+=value ]
			[/#if]
			[#if argument?index != (method.arguments?size - 1)]
				[#assign args+=", " ]
			[/#if]
		[/#list]
    [/#if]
	#n
[/#list]
#tmw_status = ${functionName}(${args});
#tif (mw_status != HSP_CORE_OK) error++;
[/#macro]

[#macro generateStructCode arg]
    [#if !arg.name?? || !arg.typeName??]
         [#return]
    [/#if]
    [#assign name =arg.name]
    [#assign type= arg.typeName]
#n
    #t${type} ${name};
    [#list arg.argument as subArgument]
        [#if !subArgument.name?? || !subArgument.value??]
             [#continue]
        [/#if]
        #t${name}.${subArgument.name} = ${subArgument.value};
    [/#list]
[/#macro]
[#-- macro generate Processing List Body End--]